#!/bin/bash

echo Deleting cpp and pyd files in Pygameshader directory prior installation
cd PygameShader
rm *.cpp
rm *.pyd
rm *.so
cd ..

python3.6 setup.py build_ext --inplace && python3.6 setup.py sdist bdist_wheel

cd PygameShader
rm *.cpp
rm *.so
cd ..

python3.7 setup.py build_ext --inplace && python3.7 setup.py sdist bdist_wheel


cd PygameShader
rm *.cpp
rm *.so
cd ..

python3.8 setup.py build_ext --inplace && python3.8 setup.py sdist bdist_wheel


cd PygameShader
rm *.cpp
rm *.so
cd ..

python3.9 setup.py build_ext --inplace && python3.9 setup.py sdist bdist_wheel


cd PygameShader
rm *.cpp
rm *.so
cd ..

python3.10 setup.py build_ext --inplace && python3.10 setup.py sdist bdist_wheel


cd PygameShader
rm *.cpp
rm *.so
cd ..

python3.11 setup.py build_ext --inplace && python3.11 setup.py sdist bdist_wheel

cd PygameShader
rm *.cpp
rm *.so
cd ..


